### ISSUE TITLE
Fix Materials Unit Label

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#313]
Change "Vd" to "Yd" (for yard - unit of measure) in all Materials locations.  This is a typo under the Settings tabs (Client, Customer, Sites).

![asdfasdfasf](https://cloud.githubusercontent.com/assets/2980580/23389943/e24fcbac-fd1f-11e6-8663-615b6130e354.png)

**Comment by JohnKJohansen-MDS** [comment]
resolved in 0.5.7 branch, public/modules/core/services/constants.js. Will not close until tested.

**Comment by muirdata** [comment]
Still seeing "vd" in Staging. How do I gain access to the fix?

**Comment by JohnKJohansen-MDS** [comment]
Fixed in Staging

**Comment by muirdata** [comment]
Looks good.

![image](https://cloud.githubusercontent.com/assets/2980580/24069389/66c2e1f6-0b64-11e7-8247-01916c144614.png)
